---
- name: Install Java
  yum: 
     name:  java-1.8.0-openjdk-devel
     state: latest
     
- name: Download Maven
  unarchive:
       src: "http://www.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz"
       dest: /opt
       copy: no

- name: Create maven symlink
  file:
      src: "/opt/apache-maven-3.0.5/bin/mvn"
      dest: /usr/bin/mvn
      state: link
      force: yes

- name: Configure maven and environment variables
  lineinfile:
      dest: "/etc/profile.d/maven.sh"
      line: "{{item.line}}"
      create: yes
      state: present
  with_items:
      - { line: 'M2_HOME=/opt/apache-maven-3.0.5' }
      - { line: 'PATH=$PATH:$M2_HOME/bin' }

- name: Make it available globally
  shell: "source /etc/profile.d/maven.sh"
