---
- hosts: localhost
  tasks:
    - name: Install roles from Ansible Galaxy
      shell: ansible-galaxy install "{{ item }}"
      with_items:
        - geerlingguy.docker
        - andrewrothstein.docker-compose
