---
# tasks file for artifactory-instance-role
- name: "create work directory"
  include: create-work-dir.yaml
- name: "Install Docker Compose"
  include: docker-compose.yaml
- name: "copy docker compose file"
  include: copy-docker-compose.yaml
- name: "copy nexus service file"
  include: copy-nexus-service.yaml
- name: "enable and start nexus service"
  include: enable-nexus-service.yaml
